### ISSUE TITLE
Could not connect error

### ISSUE THREAD

**Issue by Wolletje01** [Abadima/RPC#1]
Hey, I got this error:
```js
Error: Could not connect
    at Socket.onerror (/home/runner/mongodb-compass/node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at Object.onceWrapper (events.js:483:26)
    at Socket.emit (events.js:376:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
 
```

On windows 10 it works, but on replit it doesnt. Is there anyway of how to fix it?

**Comment by Abadima** [comment]
Hello! Unfortunately, we don't support repl.it at this time, as the way it works, is as an "application" that your client would have to recognize, if you try to do it on your own operating system (Linux, Windows, macOS) it should work just fine, otherwise try using environment variables with replit instead of .env

If you need anything else, don't be afraid to pull a new issue :)

**Comment by Wolletje01** [comment]
> Hello! Unfortunately, we don't support repl.it at this time, as the way it works, is as an "application" that your client would have to recognize, if you try to do it on your own operating system (Linux, Windows, macOS) it should work just fine, otherwise try using environment variables with replit instead of .env
> 
> If you need anything else, don't be afraid to pull a new issue :)

the environment variables doesnt work with this either, so i'm gonna host it on my own pc.
